# Generated by Django 5.2.4 on 2025-09-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bill_razorpay_order_id_bill_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='razorpay_payment_id',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_appointments', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='myapp.doctor')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('time_slot', 'status')},
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Confirmed'])), fields=('time_slot',), name='unique_active_appointment_per_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
