# Generated by Django 5.2.4 on 2025-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bill_feedback_payment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='lab_test_charges',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='medication_charges',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='other_charges',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax',
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
